import type { ISeriesPrimitive, ISeriesPrimitivePaneRenderer, ISeriesPrimitivePaneView, SeriesAttachedParameter, Time } from "@/lib/lightweightChartsCompat";
import type { ConfirmedSweepEvent, LiquidityStopSweepFrame, LiquidityStopSweepSettings } from "@/lib/liquidityStopSweepDetector";

type CandleSeriesApi = SeriesAttachedParameter<Time, "Candlestick">["series"];
export type LiquidityStopSweepPrimitiveData = { frame: LiquidityStopSweepFrame; settings: LiquidityStopSweepSettings; backgroundColor: string };
export type LiquidityStopSweepHit = { x: number; y: number; event: ConfirmedSweepEvent };
type Bound = { left: number; top: number; right: number; bottom: number; hit: LiquidityStopSweepHit };
const clamp = (value: number, minimum = 0, maximum = 1) => Math.max(minimum, Math.min(maximum, value));
function rgba(color: string, alpha: number) { const match = /^#([0-9a-f]{3}|[0-9a-f]{6})$/i.exec(color); if (!match) return color; const hex = match[1].length === 3 ? match[1].split("").map((part) => part + part).join("") : match[1]; const value = Number.parseInt(hex, 16); return `rgba(${value >> 16},${(value >> 8) & 255},${value & 255},${clamp(alpha)})`; }
const compact = (value: number) => Math.abs(value) >= 1_000_000 ? `${(value / 1_000_000).toFixed(1)}M` : Math.abs(value) >= 1_000 ? `${(value / 1_000).toFixed(1)}K` : Math.round(value).toLocaleString();

class Renderer implements ISeriesPrimitivePaneRenderer {
  constructor(private readonly primitive: LiquidityStopSweepPrimitive) {}
  draw(target: Parameters<ISeriesPrimitivePaneRenderer["draw"]>[0]) {
    const data = this.primitive.data(); const chart = this.primitive.chart(); const series = this.primitive.series(); if (!data || !chart || !series) return;
    target.useMediaCoordinateSpace(({ context, mediaSize }) => {
      if (mediaSize.width < 100 || mediaSize.height < 80) return; const { frame, settings } = data; const opacity = settings.opacity / 100; const bounds: Bound[] = []; const hybrid = settings.visualizationMode === "hybrid"; const drawBands = settings.showPriceTimeBands && (hybrid || settings.visualizationMode === "price-time-bands"); const drawZones = settings.showStopSweepZones && (hybrid || settings.visualizationMode === "stop-sweep-zones"); const drawBrackets = settings.showRangeBrackets && (hybrid || settings.visualizationMode === "range-brackets"); const drawMarkers = settings.showMarkers && (hybrid || settings.visualizationMode === "event-markers" || settings.visualizationMode === "lower-pane"); const drawLane = settings.showActiveLane && (hybrid || settings.visualizationMode === "active-event-lane");
      const timeToX = (timestamp: number) => chart.timeScale().timeToCoordinate(Math.floor(timestamp / 1_000) as Time); const priceToY = (tick: number) => series.priceToCoordinate(tick * frame.tickSize); const colorFor = (event: ConfirmedSweepEvent) => event.state === "rejected" ? settings.rejectionColor : event.state === "possible-stop-sweep" ? settings.warningColor : event.direction === "buy" ? settings.buyColor : settings.sellColor;
      context.save(); context.beginPath(); context.rect(0, 0, mediaSize.width, mediaSize.height); context.clip();
      for (const event of frame.events) {
        const start = timeToX(event.startMs); const end = timeToX(event.endMs); const high = priceToY(event.highTick + 0.5); const low = priceToY(event.lowTick - 0.5); if (start === null || end === null || high === null || low === null) continue; const x1 = Number(start); const x2 = Math.max(x1 + 2, Number(end)); const top = Math.min(Number(high), Number(low)); const bottom = Math.max(Number(high), Number(low)); const color = colorFor(event); const scoreScale = clamp(event.score / 100, 0.25, 1);
        if (drawBands) { context.fillStyle = rgba(color, opacity * 0.045 * scoreScale); context.fillRect(x1, top, Math.min(80, Math.max(2, x2 - x1)), Math.max(2, bottom - top)); context.strokeStyle = rgba(color, opacity * 0.32); context.lineWidth = 1; context.strokeRect(x1, top, Math.min(80, Math.max(2, x2 - x1)), Math.max(2, bottom - top)); }
        if (drawZones && event.primaryReference) { const referenceY = priceToY(event.primaryReference.priceTick); const extremeY = priceToY(event.direction === "buy" ? event.highTick : event.lowTick); if (referenceY !== null && extremeY !== null) { const zoneTop = Math.min(Number(referenceY), Number(extremeY)); const zoneBottom = Math.max(Number(referenceY), Number(extremeY)); const zoneRight = event.state === "possible-stop-sweep" ? mediaSize.width - (drawLane ? settings.activeLaneWidth : 0) : Math.min(mediaSize.width, x2 + 70); context.fillStyle = rgba(color, opacity * (event.state === "rejected" ? 0.065 : event.state === "continuing" ? 0.055 : 0.035)); context.fillRect(x1, zoneTop, Math.max(2, zoneRight - x1), Math.max(2, zoneBottom - zoneTop)); context.strokeStyle = rgba(settings.warningColor, opacity * 0.62); context.setLineDash([4, 4]); context.beginPath(); context.moveTo(x1, Number(referenceY)); context.lineTo(zoneRight, Number(referenceY)); context.stroke(); context.setLineDash([]); } }
        if (drawBrackets) { const bx = Math.max(x1, x2); const cap = 6; context.strokeStyle = rgba(color, opacity * (0.55 + 0.4 * scoreScale)); context.lineWidth = 1.5; context.beginPath(); context.moveTo(bx, top); context.lineTo(bx, bottom); context.moveTo(bx, top); context.lineTo(bx + (event.direction === "buy" ? cap : -cap), top); context.moveTo(bx, bottom); context.lineTo(bx + (event.direction === "buy" ? cap : -cap), bottom); context.stroke(); }
        const extremeY = priceToY(event.direction === "buy" ? event.highTick : event.lowTick); if (drawMarkers && extremeY !== null) { const cx = x2 + 2; const cy = Number(extremeY); const size = settings.markerSize + Math.min(5, event.score / 25); context.strokeStyle = rgba(color, opacity); context.lineWidth = 1.5; context.beginPath(); if (event.direction === "buy") { context.moveTo(cx - size, cy + size / 2); context.lineTo(cx, cy - size / 2); context.lineTo(cx + size, cy + size / 2); context.moveTo(cx - size, cy + size); context.lineTo(cx, cy); context.lineTo(cx + size, cy + size); } else { context.moveTo(cx - size, cy - size / 2); context.lineTo(cx, cy + size / 2); context.lineTo(cx + size, cy - size / 2); context.moveTo(cx - size, cy - size); context.lineTo(cx, cy); context.lineTo(cx + size, cy - size); } context.stroke(); if (event.state === "rejected") { context.beginPath(); context.arc(cx, cy, size * 0.65, Math.PI * 0.15, Math.PI * 1.55); context.stroke(); } if (settings.showLabels && event.score >= settings.minimumLaneScore) { context.fillStyle = rgba(color, opacity); context.font = "600 8px JetBrains Mono, monospace"; context.textAlign = event.direction === "buy" ? "left" : "right"; context.textBaseline = "middle"; const state = event.state === "possible-stop-sweep" ? "STOP?" : event.state === "continuing" ? "CONT" : event.state === "rejected" ? "REJECT" : event.state === "exhausted" ? "EXHAUST" : "SWEEP"; context.fillText(`${event.direction.toUpperCase()} ${state} · ${compact(event.totalQuantity)} · ${event.uniqueLevelCount}L · ${event.score}`, cx + (event.direction === "buy" ? size + 4 : -size - 4), cy); } bounds.push({ left: cx - size, top: cy - size, right: cx + size, bottom: cy + size, hit: { x: cx, y: cy, event } }); }
      }
      if (drawLane) { const laneRight = mediaSize.width - 3; const laneLeft = Math.max(0, laneRight - settings.activeLaneWidth); context.fillStyle = rgba(data.backgroundColor, 0.9); context.fillRect(laneLeft, 0, settings.activeLaneWidth + 3, mediaSize.height); context.strokeStyle = rgba(settings.neutralColor, 0.22); context.beginPath(); context.moveTo(laneLeft, 0); context.lineTo(laneLeft, mediaSize.height); context.stroke(); const active = frame.events.filter((event) => event.score >= settings.minimumLaneScore).sort((a, b) => b.endMs - a.endMs || b.score - a.score).slice(0, settings.maximumActiveLaneRows); const maximum = Math.max(1, ...active.map((event) => event.totalQuantity)); for (const event of active) { const anchorTick = event.primaryReference?.priceTick ?? (event.direction === "buy" ? event.highTick : event.lowTick); const y = priceToY(anchorTick); if (y === null) continue; const color = colorFor(event); const width = Math.max(26, (settings.activeLaneWidth - 6) * Math.sqrt(event.totalQuantity / maximum)); const height = 18; context.fillStyle = rgba(color, opacity * 0.28); context.fillRect(laneRight - width, Number(y) - height / 2, width, height); context.strokeStyle = rgba(color, opacity * 0.72); context.strokeRect(laneRight - width, Number(y) - height / 2, width, height); context.fillStyle = rgba("#FFFFFF", 0.92); context.font = "600 7px JetBrains Mono, monospace"; context.textAlign = "right"; context.textBaseline = "middle"; const state = event.state === "possible-stop-sweep" ? "STOP?" : event.state === "continuing" ? "CONT" : event.state === "rejected" ? "REJECT" : "SWEEP"; context.fillText(`${event.direction.toUpperCase()} ${state} · ${compact(event.totalQuantity)} · ${event.uniqueLevelCount}L · ${event.score}`, laneRight - 3, Number(y)); bounds.push({ left: laneRight - width, top: Number(y) - height / 2, right: laneRight, bottom: Number(y) + height / 2, hit: { x: laneRight - width, y: Number(y), event } }); } }
      context.restore(); this.primitive.replaceBounds(bounds);
    });
  }
}
class PaneView implements ISeriesPrimitivePaneView { constructor(private readonly primitive: LiquidityStopSweepPrimitive) {} zOrder() { return "bottom" as const; } renderer() { return new Renderer(this.primitive); } }
export class LiquidityStopSweepPrimitive implements ISeriesPrimitive<Time> { private chartApi: SeriesAttachedParameter<Time, "Candlestick">["chart"] | null = null; private seriesApi: CandleSeriesApi | null = null; private requestUpdate: (() => void) | null = null; private model: LiquidityStopSweepPrimitiveData | null = null; private bounds: Bound[] = []; private readonly view = new PaneView(this); attached(params: SeriesAttachedParameter<Time, "Candlestick">) { this.chartApi = params.chart; this.seriesApi = params.series; this.requestUpdate = params.requestUpdate; } detached() { this.chartApi = null; this.seriesApi = null; this.requestUpdate = null; this.bounds = []; } paneViews() { return this.model ? [this.view] : []; } update(model: LiquidityStopSweepPrimitiveData | null) { this.model = model; if (!model) this.bounds = []; this.requestUpdate?.(); } data() { return this.model; } chart() { return this.chartApi; } series() { return this.seriesApi; } replaceBounds(bounds: Bound[]) { this.bounds = bounds; } queryHit(x: number, y: number) { for (let index = this.bounds.length - 1; index >= 0; index -= 1) { const bound = this.bounds[index]; if (x >= bound.left && x <= bound.right && y >= bound.top && y <= bound.bottom) return { ...bound.hit, x, y }; } return null; } }
