"use client";

import { useState } from "react";
import { Bell, Database, Eye, MapPin, Palette, Save, Tags, X } from "lucide-react";
import ChartColorField from "@/components/ChartColorField";
import type { PrecisionObject, PrecisionStyle, PrecisionToolConfig } from "./types";

type Tab = "Style" | "Labels" | "Coordinates" | "Data" | "Alert" | "Visibility" | "Tool Configs";
const tabs: Array<{ id: Tab; icon: typeof Palette }> = [
  { id: "Style", icon: Palette }, { id: "Labels", icon: Tags }, { id: "Coordinates", icon: MapPin },
  { id: "Data", icon: Database }, { id: "Alert", icon: Bell }, { id: "Visibility", icon: Eye },
  { id: "Tool Configs", icon: Save },
];

interface Props {
  object: PrecisionObject | null;
  configs: PrecisionToolConfig[];
  activeSlot: number;
  onSlot: (slot: number) => void;
  onClose: () => void;
  onUpdate: (updater: (object: PrecisionObject) => PrecisionObject) => void;
  onSaveConfig: () => void;
  onResetConfig: () => void;
}

const inputClass = "h-8 w-full border border-[#314157] bg-[#0a111b] px-2 font-mono text-[9px] text-[#c8d3e1] outline-none focus:border-[#68a8ff]";
const sectionTitle = "mb-2 font-mono text-[8px] font-bold uppercase tracking-[.14em] text-[#71839a]";

function optionLabel(value: string): string {
  return value.replace(/([a-z])([A-Z])/g, "$1 $2").replaceAll("_", " ").replace(/^./, (letter) => letter.toUpperCase());
}

export default function PrecisionSettingsDrawer({ object, configs, activeSlot, onSlot, onClose, onUpdate, onSaveConfig, onResetConfig }: Props) {
  const [tab, setTab] = useState<Tab>("Style");
  const updateStyle = (patch: Partial<PrecisionStyle>) => onUpdate((value) => ({ ...value, style: { ...value.style, ...patch } }));

  return <aside className="pointer-events-auto absolute bottom-0 right-0 top-0 z-[75] w-[370px] border-l border-[#33465e] bg-[#080e16]/[.985] shadow-[-20px_0_65px_#000d] backdrop-blur-xl">
    <header className="flex h-11 items-center justify-between border-b border-[#29394d] px-3"><div><div className="font-mono text-[8px] font-bold uppercase tracking-[.18em] text-[#6f8199]">Precision Tools</div><div className="mt-0.5 font-mono text-[10px] font-semibold text-[#d2dbe7]">{object?.name ?? "Defaults & tool configs"}</div></div><button type="button" onClick={onClose}><X className="h-4 w-4 text-[#74869e] hover:text-white" /></button></header>
    <nav className="flex h-10 overflow-x-auto border-b border-[#29394d] px-1">{tabs.map(({ id, icon: Icon }) => <button key={id} type="button" onClick={() => setTab(id)} className={`flex shrink-0 items-center gap-1 border-b px-2 font-mono text-[7px] font-bold uppercase tracking-[.08em] ${tab === id ? "border-[#68a8ff] text-[#9ac6ff]" : "border-transparent text-[#667890]"}`}><Icon className="h-3 w-3" />{id}</button>)}</nav>
    <div className="h-[calc(100%-84px)] overflow-y-auto p-4">
      {!object && tab !== "Tool Configs" ? <div className="border border-dashed border-[#2b3c50] p-5 text-center font-mono text-[9px] leading-5 text-[#718299]">Select a Precision object to edit its {tab.toLowerCase()}.</div> : null}

      {object && tab === "Style" ? <div className="space-y-4">
        <section><div className={sectionTitle}>Stroke</div><div className="grid grid-cols-2 gap-2"><div className="font-mono text-[8px] text-[#7789a0]">Colour<div className="mt-1"><ChartColorField ariaLabel="Stroke colour" value={object.style.stroke} onChange={(hex) => updateStyle({ stroke: hex })} /></div></div><label className="font-mono text-[8px] text-[#7789a0]">Width<input type="number" min="0.5" max="8" step="0.25" value={object.style.strokeWidth} onChange={(event) => updateStyle({ strokeWidth: Number(event.target.value) })} className={`mt-1 ${inputClass}`} /></label></div></section>
        <section><div className={sectionTitle}>Line & opacity</div><select value={object.style.lineStyle} onChange={(event) => updateStyle({ lineStyle: event.target.value as PrecisionStyle["lineStyle"] })} className={inputClass}><option value="solid">Solid</option><option value="dashed">Dashed</option><option value="dotted">Dotted</option></select><label className="mt-3 block font-mono text-[8px] text-[#7789a0]">Opacity · {Math.round(object.style.opacity * 100)}%<input type="range" min="0.1" max="1" step="0.01" value={object.style.opacity} onChange={(event) => updateStyle({ opacity: Number(event.target.value) })} className="mt-1 w-full accent-[#68a8ff]" /></label></section>
        <section><div className={sectionTitle}>Fill</div><div className="grid grid-cols-2 gap-2"><ChartColorField ariaLabel="Fill colour" value={object.style.fill} onChange={(hex) => updateStyle({ fill: hex })} /><label className="font-mono text-[8px] text-[#7789a0]">{Math.round(object.style.fillOpacity * 100)}%<input type="range" min="0" max="0.8" step="0.01" value={object.style.fillOpacity} onChange={(event) => updateStyle({ fillOpacity: Number(event.target.value) })} className="w-full accent-[#68a8ff]" /></label></div></section>
        <section><div className={sectionTitle}>Analytical colours</div><div className="grid grid-cols-3 gap-2">{(["positiveColor", "negativeColor", "neutralColor", "valueAreaColor", "pocColor"] as const).map((key) => <div key={key} className="font-mono text-[7px] text-[#7789a0]">{optionLabel(key)}<div className="mt-1"><ChartColorField ariaLabel={`${optionLabel(key)} colour`} value={object.style[key]} onChange={(hex) => updateStyle({ [key]: hex })} /></div></div>)}</div></section>
        <section><div className={sectionTitle}>Typography</div><div className="grid grid-cols-2 gap-2"><input aria-label="Font family" value={object.style.fontFamily} onChange={(event) => updateStyle({ fontFamily: event.target.value })} className={inputClass}/><input aria-label="Font size" type="number" min="7" max="32" value={object.style.fontSize} onChange={(event) => updateStyle({ fontSize: Number(event.target.value) })} className={inputClass}/><select value={object.style.fontWeight} onChange={(event) => updateStyle({ fontWeight: Number(event.target.value) })} className={inputClass}><option value="400">Regular</option><option value="600">Semibold</option><option value="700">Bold</option></select></div></section>
      </div> : null}

      {object && tab === "Labels" ? <div className="space-y-3"><label className="flex items-center justify-between font-mono text-[9px] text-[#93a2b7]">Visible<input type="checkbox" checked={object.labels.visible} onChange={(event) => onUpdate((value) => ({ ...value, labels: { ...value.labels, visible: event.target.checked } }))} /></label><label className="block font-mono text-[8px] text-[#7789a0]">Label<input value={object.labels.text} onChange={(event) => onUpdate((value) => ({ ...value, labels: { ...value.labels, text: event.target.value } }))} className={`mt-1 ${inputClass}`} /></label><label className="block font-mono text-[8px] text-[#7789a0]">Position<select value={object.labels.position} onChange={(event) => onUpdate((value) => ({ ...value, labels: { ...value.labels, position: event.target.value as typeof value.labels.position } }))} className={`mt-1 ${inputClass}`}>{["start", "middle", "end", "top", "bottom"].map((position) => <option key={position} value={position}>{optionLabel(position)}</option>)}</select></label>{object.toolId === "precision-text" ? <label className="block font-mono text-[8px] text-[#7789a0]">Text<textarea value={object.text ?? ""} onChange={(event) => onUpdate((value) => ({ ...value, text: event.target.value }))} className="mt-1 min-h-24 w-full border border-[#314157] bg-[#0a111b] p-2 font-mono text-[10px] text-[#c8d3e1] outline-none focus:border-[#68a8ff]" /></label> : null}{(["showPrice", "showTime", "showMetrics"] as const).map((key) => <label key={key} className="flex items-center justify-between font-mono text-[9px] text-[#93a2b7]">{optionLabel(key)}<input type="checkbox" checked={object.labels[key]} onChange={(event) => onUpdate((value) => ({ ...value, labels: { ...value.labels, [key]: event.target.checked } }))} /></label>)}</div> : null}

      {object && tab === "Coordinates" ? <div className="space-y-3">{object.anchors.map((anchor, index) => <div key={index} className="border border-[#29394d] bg-[#0b131e] p-2"><div className={sectionTitle}>Anchor {index + 1}</div><div className="grid grid-cols-2 gap-2"><label className="font-mono text-[7px] text-[#71839a]">Time<input type="datetime-local" value={new Date(anchor.time - new Date().getTimezoneOffset() * 60_000).toISOString().slice(0, 16)} onChange={(event) => onUpdate((value) => ({ ...value, anchors: value.anchors.map((candidate, cursor) => cursor === index ? { ...candidate, time: new Date(event.target.value).getTime() } : candidate) }))} className={`mt-1 ${inputClass}`} /></label><label className="font-mono text-[7px] text-[#71839a]">Price<input type="number" step="any" value={anchor.price} onChange={(event) => onUpdate((value) => ({ ...value, anchors: value.anchors.map((candidate, cursor) => cursor === index ? { ...candidate, price: Number(event.target.value) } : candidate) }))} className={`mt-1 ${inputClass}`} /></label></div></div>)}</div> : null}

      {object && tab === "Data" ? <div className="space-y-3"><div className="border border-[#2d4056] bg-[#0b141f] p-3 font-mono text-[8px] leading-5 text-[#8e9db0]">Analytics use the chart&apos;s read-only market-data adapters. Volume Profile accepts executed trades only. Anchored VWAP accepts native bar volume only. Missing data is shown honestly.</div>{Object.entries(object.options).map(([key, value]) => typeof value === "boolean" ? <label key={key} className="flex items-center justify-between font-mono text-[8px] text-[#8fa0b5]">{optionLabel(key)}<input type="checkbox" checked={value} onChange={(event) => onUpdate((item) => ({ ...item, options: { ...item.options, [key]: event.target.checked } }))} /></label> : typeof value === "number" ? <label key={key} className="block font-mono text-[8px] text-[#7789a0]">{optionLabel(key)}<input type="number" value={value} step="any" onChange={(event) => onUpdate((item) => ({ ...item, options: { ...item.options, [key]: Number(event.target.value) } }))} className={`mt-1 ${inputClass}`} /></label> : Array.isArray(value) ? <label key={key} className="block font-mono text-[8px] text-[#7789a0]">{optionLabel(key)}<input value={value.join(", ")} onChange={(event) => onUpdate((item) => ({ ...item, options: { ...item.options, [key]: event.target.value.split(",").map(Number).filter(Number.isFinite) } }))} className={`mt-1 ${inputClass}`} /></label> : <label key={key} className="block font-mono text-[8px] text-[#7789a0]">{optionLabel(key)}<input value={String(value)} onChange={(event) => onUpdate((item) => ({ ...item, options: { ...item.options, [key]: event.target.value } }))} className={`mt-1 ${inputClass}`} /></label>)}</div> : null}

      {object && tab === "Alert" ? <div className="space-y-3"><button type="button" onClick={() => onUpdate((value) => ({ ...value, alert: value.alert ? null : { id: `precision-alert-${Date.now()}`, enabled: true, condition: "cross", once: false, message: `${value.name} alert`, lastTriggeredAt: null } }))} className="h-9 w-full border border-[#3b5270] bg-[#132137] font-mono text-[9px] font-bold uppercase text-[#9bc7ff]">{object.alert ? "Remove alert" : "Add alert"}</button>{object.alert ? <><label className="flex items-center justify-between font-mono text-[9px] text-[#93a2b7]">Enabled<input type="checkbox" checked={object.alert.enabled} onChange={(event) => onUpdate((value) => ({ ...value, alert: value.alert ? { ...value.alert, enabled: event.target.checked } : null }))} /></label><label className="flex items-center justify-between font-mono text-[9px] text-[#93a2b7]">Trigger once<input type="checkbox" checked={object.alert.once} onChange={(event) => onUpdate((value) => ({ ...value, alert: value.alert ? { ...value.alert, once: event.target.checked } : null }))} /></label><select value={object.alert.condition} onChange={(event) => onUpdate((value) => ({ ...value, alert: value.alert ? { ...value.alert, condition: event.target.value as NonNullable<PrecisionObject["alert"]>["condition"] } : null }))} className={inputClass}><option value="cross">Cross</option><option value="cross-up">Cross up</option><option value="cross-down">Cross down</option><option value="enter">Enter</option><option value="exit">Exit</option></select><input value={object.alert.message} onChange={(event) => onUpdate((value) => ({ ...value, alert: value.alert ? { ...value.alert, message: event.target.value } : null }))} className={inputClass}/>{object.alert.lastTriggeredAt ? <div className="border border-[#2d4056] bg-[#0b141f] p-2 font-mono text-[8px] text-[#8798ae]">Last triggered {new Date(object.alert.lastTriggeredAt).toLocaleString()}</div> : null}</> : null}</div> : null}

      {object && tab === "Visibility" ? <div className="space-y-3">{(["visible", "locked"] as const).map((key) => <label key={key} className="flex items-center justify-between font-mono text-[9px] capitalize text-[#93a2b7]">{key}<input type="checkbox" checked={object.visibility[key]} onChange={(event) => onUpdate((value) => ({ ...value, visibility: { ...value.visibility, [key]: event.target.checked } }))} /></label>)}<label className="block font-mono text-[8px] text-[#7789a0]">Timeframes (comma separated)<input value={object.visibility.timeframes.join(",")} onChange={(event) => onUpdate((value) => ({ ...value, visibility: { ...value.visibility, timeframes: event.target.value.split(",").map((item) => item.trim()).filter(Boolean) } }))} className={`mt-1 ${inputClass}`} /></label><div className="grid grid-cols-2 gap-2"><label className="font-mono text-[8px] text-[#7789a0]">Min zoom (px/bar)<input type="number" min="0" step="0.25" value={object.visibility.minZoom ?? ""} onChange={(event) => onUpdate((value) => ({ ...value, visibility: { ...value.visibility, minZoom: event.target.value === "" ? null : Number(event.target.value) } }))} className={`mt-1 ${inputClass}`} /></label><label className="font-mono text-[8px] text-[#7789a0]">Max zoom (px/bar)<input type="number" min="0" step="0.25" value={object.visibility.maxZoom ?? ""} onChange={(event) => onUpdate((value) => ({ ...value, visibility: { ...value.visibility, maxZoom: event.target.value === "" ? null : Number(event.target.value) } }))} className={`mt-1 ${inputClass}`} /></label></div></div> : null}

      {tab === "Tool Configs" ? <div><div className={sectionTitle}>Nine independent configuration slots</div><div className="grid grid-cols-3 gap-2">{Array.from({ length: 9 }, (_, index) => index + 1).map((slot) => <button key={slot} type="button" onClick={() => onSlot(slot)} className={`h-9 border font-mono text-[9px] font-bold ${activeSlot === slot ? "border-[#68a8ff] bg-[#17263a] text-[#9cc8ff]" : "border-[#2d3f55] bg-[#0b131e] text-[#71849b]"}`}>TC{slot}</button>)}</div><div className="mt-4 border border-[#29394d] bg-[#0b131e] p-3 font-mono text-[8px] leading-5 text-[#8393a8]">{object ? `Save ${object.name} style, labels and data settings into TC${activeSlot}.` : "Select an object, then save its configuration into a slot."}<div className="mt-3 grid grid-cols-2 gap-2"><button type="button" onClick={onSaveConfig} disabled={!object} className="h-9 border border-[#46658a] bg-[#14243a] font-bold uppercase text-[#9bc7ff] disabled:opacity-30">Save TC{activeSlot}</button><button type="button" onClick={onResetConfig} className="h-9 border border-[#3a4657] bg-[#111821] font-bold uppercase text-[#9aa7b7]">Reset</button></div></div>{object ? <div className="mt-3 font-mono text-[8px] text-[#667890]">Active config: {configs.find((config) => config.toolId === object.toolId && config.slot === activeSlot)?.name ?? `TC${activeSlot}`}</div> : null}</div> : null}
    </div>
  </aside>;
}
