import type { ChartSettings } from "@/lib/chartSettings";
import { VOLUME_PROFILE_GRADIENT_OFF } from "@/lib/volumeProfileGradients";
import {
  TPO_SETTINGS_SCHEMA_VERSION,
  type TpoIndicatorSettings,
  type TpoIndicatorVariant,
} from "@/lib/tpo/types";

const validTime = (value: unknown, fallback: string) =>
  typeof value === "string" && /^([01]\d|2[0-3]):[0-5]\d(?::[0-5]\d)?$/.test(value) ? value : fallback;

const finite = (value: unknown, fallback: number, min: number, max: number) => {
  const parsed = Number(value);
  return Number.isFinite(parsed) ? Math.min(max, Math.max(min, parsed)) : fallback;
};

const validTimeZone = (value: unknown, fallback: string) => {
  if (typeof value !== "string" || !value.trim()) return fallback;
  try {
    new Intl.DateTimeFormat("en-US", { timeZone: value }).format(new Date(0));
    return value;
  } catch {
    return fallback;
  }
};

export function defaultTpoSettings(
  variant: TpoIndicatorVariant,
  theme?: Pick<ChartSettings, "upColor" | "downColor" | "borderUpColor" | "borderDownColor">,
): TpoIndicatorSettings {
  const weekly = variant === "weekly-tpo";
  return {
    schemaVersion: TPO_SETTINGS_SCHEMA_VERSION,
    indicatorVariant: variant,
    scheduleKind: weekly ? "weekly" : "daily",
    periodMode: "multiple-profiles",
    lengthValue: 1,
    lengthUnit: weekly ? "week" : "day",
    timezone: "America/Chicago",
    dailyStartTime: "17:00:00",
    dailyEndMode: "next-daily-start",
    dailyEndTime: "16:00:00",
    enabledWeekdays: [0, 1, 2, 3, 4],
    weekStartDay: 0,
    weekStartTime: "17:00:00",
    weekEndMode: "next-week-start",
    weekEndDay: 5,
    weekEndTime: "16:00:00",
    weekLength: 1,
    customStartMs: null,
    customEndMs: null,
    customEndFollowsLatest: false,
    subperiodMinutes: 30,
    displayType: "blocks",
    splitMode: "none",
    profileCount: weekly ? 8 : 10,
    visitSource: "automatic",
    groupingMode: "automatic",
    ticksPerRow: 1,
    autoTargetRows: 90,
    autoGroupFactor: 1,
    freezeActiveGrouping: true,
    valueAreaPercent: 70,
    showPoc: true,
    showDevelopingPoc: true,
    showValueArea: true,
    showDevelopingValueArea: false,
    showInitialBalance: true,
    initialBalanceSubperiods: 2,
    showSinglePrints: true,
    singlePrintMaxTpoCount: 1,
    minimumSinglePrintTicks: 1,
    singlePrintQuality: 0,
    singlePrintVolumeSensitivity: 0,
    includeExtremesInSinglePrints: false,
    showPeaks: false,
    showValleys: false,
    peakValleyRadius: 2,
    peakMinimumProminence: 2,
    peakValleySensitivity: 40,
    peakValleyExcludeExtremes: true,
    showSummary: false,
    widthMode: "automatic",
    currentWidth: 100,
    currentOffset: 0,
    previousWidth: 80,
    previousOffset: 0,
    showOnRight: false,
    mirror: false,
    lockPosition: false,
    showAboveBars: true,
    opacityPercent: 72,
    borderWidth: 0.75,
    blockSize: 8,
    blockGap: 1,
    minimumTextSize: 7,
    maximumTextSize: 11,
    gradientPreset: VOLUME_PROFILE_GRADIENT_OFF,
    colourCalculation: "time",
    colourReference: "fixed",
    fixedVolumeColor: theme?.borderUpColor ?? "#22D3EE",
    fixedBidColor: theme?.downColor ?? "#FB7185",
    fixedAskColor: theme?.upColor ?? "#22D3EE",
    range1Enabled: true,
    range1Minimum: 0,
    range1VolumeColor: "#64748B",
    range1BidColor: theme?.downColor ?? "#FB7185",
    range1AskColor: theme?.upColor ?? "#22D3EE",
    range2Enabled: true,
    range2Minimum: 25,
    range2VolumeColor: "#38BDF8",
    range2BidColor: "#F43F5E",
    range2AskColor: "#06B6D4",
    range3Enabled: true,
    range3Minimum: 50,
    range3VolumeColor: "#8B5CF6",
    range3BidColor: "#E11D48",
    range3AskColor: "#0891B2",
    range4Enabled: true,
    range4Minimum: 75,
    range4VolumeColor: "#F59E0B",
    range4BidColor: "#BE123C",
    range4AskColor: "#0E7490",
    initialAColorEnabled: false,
    initialAColor: "#F59E0B",
    initialBColorEnabled: false,
    initialBColor: "#A855F7",
    initialCColorEnabled: false,
    initialCColor: "#3B82F6",
    initialDColorEnabled: false,
    initialDColor: "#14B8A6",
    colorOpenEnabled: false,
    openColor: "#22C55E",
    colorCloseEnabled: false,
    closeColor: "#F43F5E",
    barMarkerEnabled: false,
    barMarkerStyle: "candle",
    barMarkerWidth: 1,
    barMarkerUpColor: theme?.upColor ?? "#22D3EE",
    barMarkerDownColor: theme?.downColor ?? "#FB7185",
    barMarkerShowOpenClose: true,
    pocLineMode: "final",
    pocHighlight: true,
    pocHighlightColor: "#F5B83B",
    pocLineColor: "#F5B83B",
    pocLineWidth: 1.5,
    pocExtensionMode: "none",
    developingPocStartOffset: 0,
    shiftedPocTicks: 1,
    pocGroupingOpacity: 20,
    showPocPriceLabel: true,
    valueAreaHighlight: true,
    valueAreaHighlightInside: true,
    valueAreaOutsideColor: theme?.borderDownColor ?? "#475569",
    valueAreaShowLines: true,
    valueAreaShowBackground: false,
    valueAreaBackgroundOpacity: 10,
    valueAreaExtensionMode: "none",
    valueAreaLineColor: theme?.borderUpColor ?? "#60A5FA",
    valueAreaLineWidth: 1,
    valueAreaShowLabels: true,
    singlePrintLineWidth: 1,
    // Single prints are structural levels: by default the zone square prints
    // rightward across the screen. Saved settings keep whatever was chosen.
    // Marks every step down of three or more into the profile, which is
    // what a trader reads as a low-volume shelf.
    singlePrintStepDown: 3,
    singlePrintExtensionMode: "to-next-profile",
    singlePrintFillZone: true,
    singlePrintFillOpacity: 60,
    singlePrintShowLabel: true,
    singlePrintShowTestedState: true,
    initialBalanceStartSubperiod: 0,
    initialBalanceShowHigh: true,
    initialBalanceShowLow: true,
    initialBalanceShowRangeLabel: false,
    initialBalanceShowExtensions: false,
    initialBalanceExtensionMultiples: "1,1.5,2",
    initialBalanceLineColor: "#94A3B8",
    initialBalanceLineWidth: 1,
    summaryLayout: "compact",
    summaryLocation: "top-left",
    summaryShowVolume: true,
    summaryShowTrades: true,
    summaryShowBidAsk: true,
    summaryTextColor: "#F5F7FA",
    summaryBackgroundColor: "#090B10",
    summaryBackgroundOpacity: 82,
    summaryFontSize: 8,
    filterMode: "none",
    sessionPreset: "eth",
    customSessionStart: "17:00:00",
    customSessionEnd: "16:00:00",
    useEndSessionAsStartDay: false,
    inheritThemeColours: true,
    profileColor: theme?.borderUpColor ?? theme?.upColor ?? "#22D3EE",
    pocColor: "#F5B83B",
    valueAreaColor: theme?.borderUpColor ?? "#60A5FA",
    singlePrintColor: theme?.downColor ?? "#FB7185",
    peakColor: theme?.upColor ?? "#A3E635",
    valleyColor: "#8B5CF6",
    allowDevelopingComposite: true,
    maximumMergeMembers: 30,
    maximumRenderedBlocks: 50_000,
    fpsCap: 60,
  };
}

export function validateTpoSettings(
  input: Record<string, unknown> | undefined,
  variant: TpoIndicatorVariant,
  theme?: Pick<ChartSettings, "upColor" | "downColor" | "borderUpColor" | "borderDownColor">,
): TpoIndicatorSettings {
  const defaults = defaultTpoSettings(variant, theme);
  const source = input ?? {};
  const enumValue = <T extends string>(key: string, values: readonly T[], fallback: T) =>
    values.includes(source[key] as T) ? source[key] as T : fallback;
  return {
    ...defaults,
    ...source,
    schemaVersion: TPO_SETTINGS_SCHEMA_VERSION,
    indicatorVariant: variant,
    scheduleKind: enumValue("scheduleKind", ["daily", "weekly", "generic-period", "custom-range"], defaults.scheduleKind),
    periodMode: enumValue("periodMode", ["all-loaded-bars", "multiple-profiles", "custom-range"], defaults.periodMode),
    dailyEndMode: enumValue("dailyEndMode", ["next-daily-start", "explicit-time"], defaults.dailyEndMode),
    weekEndMode: enumValue("weekEndMode", ["next-week-start", "explicit-day-time"], defaults.weekEndMode),
    lengthUnit: enumValue("lengthUnit", ["minute", "day", "week", "month"], defaults.lengthUnit),
    displayType: enumValue("displayType", ["automatic", "letters", "blocks"], defaults.displayType),
    splitMode: enumValue("splitMode", ["none", "last", "all"], defaults.splitMode),
    visitSource: enumValue("visitSource", ["exact-trades", "bar-range", "automatic"], defaults.visitSource),
    groupingMode: enumValue("groupingMode", ["automatic", "manual"], defaults.groupingMode),
    widthMode: enumValue("widthMode", ["automatic", "period-percent", "window-percent", "fixed-bars"], defaults.widthMode),
    colourCalculation: enumValue("colourCalculation", ["time", "volume", "delta"], defaults.colourCalculation),
    colourReference: enumValue("colourReference", ["fixed", "fading", "multiple-ranges"], defaults.colourReference),
    barMarkerStyle: enumValue("barMarkerStyle", ["body", "candle"], defaults.barMarkerStyle),
    pocLineMode: enumValue("pocLineMode", ["none", "final", "developing", "extend-shifted"], defaults.pocLineMode),
    pocExtensionMode: enumValue("pocExtensionMode", ["none", "until-first-interaction", "to-window-end"], defaults.pocExtensionMode),
    valueAreaExtensionMode: enumValue("valueAreaExtensionMode", ["none", "until-first-interaction", "to-window-end"], defaults.valueAreaExtensionMode),
    singlePrintStepDown: finite(source.singlePrintStepDown, defaults.singlePrintStepDown, 0, 50),
    singlePrintExtensionMode: enumValue("singlePrintExtensionMode", ["none", "until-first-interaction", "to-window-end", "to-next-profile"], defaults.singlePrintExtensionMode),
    summaryLayout: enumValue("summaryLayout", ["compact", "full"], defaults.summaryLayout),
    summaryLocation: enumValue("summaryLocation", ["top-left", "top-right", "bottom-left", "bottom-right"], defaults.summaryLocation),
    filterMode: enumValue("filterMode", ["none", "filter", "split-two", "split-three"], defaults.filterMode),
    sessionPreset: enumValue("sessionPreset", ["rth", "eth", "custom"], defaults.sessionPreset),
    timezone: validTimeZone(source.timezone, defaults.timezone),
    dailyStartTime: validTime(source.dailyStartTime, defaults.dailyStartTime),
    dailyEndTime: validTime(source.dailyEndTime, defaults.dailyEndTime),
    weekStartTime: validTime(source.weekStartTime, defaults.weekStartTime),
    weekEndTime: validTime(source.weekEndTime, defaults.weekEndTime),
    customSessionStart: validTime(source.customSessionStart, defaults.customSessionStart),
    customSessionEnd: validTime(source.customSessionEnd, defaults.customSessionEnd),
    useEndSessionAsStartDay: typeof source.useEndSessionAsStartDay === "boolean" ? source.useEndSessionAsStartDay : defaults.useEndSessionAsStartDay,
    lengthValue: finite(source.lengthValue, defaults.lengthValue, 1, 1_800_000),
    subperiodMinutes: finite(source.subperiodMinutes, 30, 1, 1_440),
    profileCount: Math.round(finite(source.profileCount, defaults.profileCount, 0, 500)),
    ticksPerRow: Math.round(finite(source.ticksPerRow, 1, 1, 600)),
    autoTargetRows: Math.round(finite(source.autoTargetRows, 90, 20, 400)),
    autoGroupFactor: finite(source.autoGroupFactor, 1, 0.25, 8),
    valueAreaPercent: finite(source.valueAreaPercent, 70, 1, 100),
    initialBalanceSubperiods: Math.round(finite(source.initialBalanceSubperiods, 2, 1, 48)),
    minimumSinglePrintTicks: Math.round(finite(source.minimumSinglePrintTicks, 1, 1, 100)),
    singlePrintQuality: Math.round(finite(source.singlePrintQuality, 0, 0, 100)),
    singlePrintVolumeSensitivity: Math.round(finite(source.singlePrintVolumeSensitivity, 0, 0, 100)),
    peakValleyRadius: Math.round(finite(source.peakValleyRadius, 2, 1, 20)),
    peakMinimumProminence: finite(source.peakMinimumProminence, 2, 0, 10_000),
    singlePrintMaxTpoCount: Math.round(finite(source.singlePrintMaxTpoCount, defaults.singlePrintMaxTpoCount, 1, 10)),
    peakValleySensitivity: Math.round(finite(source.peakValleySensitivity, defaults.peakValleySensitivity, 0, 100)),
    peakValleyExcludeExtremes: typeof source.peakValleyExcludeExtremes === "boolean" ? source.peakValleyExcludeExtremes : defaults.peakValleyExcludeExtremes,
    currentWidth: finite(source.currentWidth, 100, 0, 500),
    currentOffset: finite(source.currentOffset, 0, 0, 500),
    previousWidth: finite(source.previousWidth, 80, 0, 500),
    previousOffset: finite(source.previousOffset, 0, 0, 500),
    opacityPercent: finite(source.opacityPercent, 72, 0, 100),
    borderWidth: finite(source.borderWidth, 0.75, 0, 6),
    blockSize: finite(source.blockSize, 8, 2, 24),
    blockGap: finite(source.blockGap, 1, 0, 6),
    minimumTextSize: finite(source.minimumTextSize, 7, 5, 20),
    maximumTextSize: finite(source.maximumTextSize, 11, 5, 28),
    range1Minimum: finite(source.range1Minimum, defaults.range1Minimum, -Number.MAX_SAFE_INTEGER, Number.MAX_SAFE_INTEGER),
    range2Minimum: finite(source.range2Minimum, defaults.range2Minimum, -Number.MAX_SAFE_INTEGER, Number.MAX_SAFE_INTEGER),
    range3Minimum: finite(source.range3Minimum, defaults.range3Minimum, -Number.MAX_SAFE_INTEGER, Number.MAX_SAFE_INTEGER),
    range4Minimum: finite(source.range4Minimum, defaults.range4Minimum, -Number.MAX_SAFE_INTEGER, Number.MAX_SAFE_INTEGER),
    barMarkerWidth: finite(source.barMarkerWidth, defaults.barMarkerWidth, 0, 5),
    pocLineWidth: finite(source.pocLineWidth, defaults.pocLineWidth, 0, 10),
    developingPocStartOffset: Math.round(finite(source.developingPocStartOffset, defaults.developingPocStartOffset, 0, 32767)),
    shiftedPocTicks: Math.round(finite(source.shiftedPocTicks, defaults.shiftedPocTicks, 1, 100)),
    pocGroupingOpacity: finite(source.pocGroupingOpacity, defaults.pocGroupingOpacity, 0, 100),
    valueAreaBackgroundOpacity: finite(source.valueAreaBackgroundOpacity, defaults.valueAreaBackgroundOpacity, 0, 100),
    valueAreaLineWidth: finite(source.valueAreaLineWidth, defaults.valueAreaLineWidth, 0, 10),
    singlePrintLineWidth: finite(source.singlePrintLineWidth, defaults.singlePrintLineWidth, 0, 10),
    singlePrintFillOpacity: finite(source.singlePrintFillOpacity, defaults.singlePrintFillOpacity, 0, 100),
    initialBalanceStartSubperiod: Math.round(finite(source.initialBalanceStartSubperiod, defaults.initialBalanceStartSubperiod, 0, 32767)),
    initialBalanceLineWidth: finite(source.initialBalanceLineWidth, defaults.initialBalanceLineWidth, 0, 10),
    summaryBackgroundOpacity: finite(source.summaryBackgroundOpacity, defaults.summaryBackgroundOpacity, 0, 100),
    summaryFontSize: finite(source.summaryFontSize, defaults.summaryFontSize, 6, 24),
    weekStartDay: Math.round(finite(source.weekStartDay, 0, 0, 6)),
    weekEndDay: Math.round(finite(source.weekEndDay, 5, 0, 6)),
    weekLength: Math.round(finite(source.weekLength, 1, 1, 52)),
    maximumMergeMembers: Math.round(finite(source.maximumMergeMembers, 30, 2, 100)),
    maximumRenderedBlocks: Math.round(finite(source.maximumRenderedBlocks, 50_000, 1_000, 250_000)),
    fpsCap: Math.round(finite(source.fpsCap, 60, 15, 144)),
    customStartMs: finite(source.customStartMs, 0, 0, Number.MAX_SAFE_INTEGER) || null,
    customEndMs: finite(source.customEndMs, 0, 0, Number.MAX_SAFE_INTEGER) || null,
    enabledWeekdays: (Array.isArray(source.enabledWeekdays)
      ? source.enabledWeekdays
      : typeof source.enabledWeekdays === "string" ? source.enabledWeekdays.split(",") : defaults.enabledWeekdays)
      .map(Number).filter((day) => Number.isInteger(day) && day >= 0 && day <= 6),
  } as TpoIndicatorSettings;
}

export function tpoSettingsToRecord(settings: TpoIndicatorSettings): Record<string, number | string | boolean> {
  return {
    ...settings,
    enabledWeekdays: settings.enabledWeekdays.join(","),
    customStartMs: settings.customStartMs ?? 0,
    customEndMs: settings.customEndMs ?? 0,
  };
}

/**
 * Stable identity for the settings that change the calculated auction model.
 *
 * Drawing-only controls (colours, opacity, widths, labels and placement) are
 * intentionally excluded.  The chart can therefore repaint those controls
 * without replaying the complete execution/bar history through the TPO engine.
 */
export function tpoCalculationSettingsKey(settings: TpoIndicatorSettings): string {
  return JSON.stringify({
    schemaVersion: settings.schemaVersion,
    indicatorVariant: settings.indicatorVariant,
    scheduleKind: settings.scheduleKind,
    periodMode: settings.periodMode,
    lengthValue: settings.lengthValue,
    lengthUnit: settings.lengthUnit,
    timezone: settings.timezone,
    dailyStartTime: settings.dailyStartTime,
    dailyEndMode: settings.dailyEndMode,
    dailyEndTime: settings.dailyEndTime,
    enabledWeekdays: settings.enabledWeekdays,
    weekStartDay: settings.weekStartDay,
    weekStartTime: settings.weekStartTime,
    weekEndMode: settings.weekEndMode,
    weekEndDay: settings.weekEndDay,
    weekEndTime: settings.weekEndTime,
    weekLength: settings.weekLength,
    customStartMs: settings.customStartMs,
    customEndMs: settings.customEndMs,
    customEndFollowsLatest: settings.customEndFollowsLatest,
    subperiodMinutes: settings.subperiodMinutes,
    profileCount: settings.profileCount,
    visitSource: settings.visitSource,
    groupingMode: settings.groupingMode,
    ticksPerRow: settings.ticksPerRow,
    autoTargetRows: settings.autoTargetRows,
    autoGroupFactor: settings.autoGroupFactor,
    freezeActiveGrouping: settings.freezeActiveGrouping,
    valueAreaPercent: settings.valueAreaPercent,
    initialBalanceSubperiods: settings.initialBalanceSubperiods,
    initialBalanceStartSubperiod: settings.initialBalanceStartSubperiod,
    minimumSinglePrintTicks: settings.minimumSinglePrintTicks,
    singlePrintQuality: settings.singlePrintQuality,
    singlePrintVolumeSensitivity: settings.singlePrintVolumeSensitivity,
    includeExtremesInSinglePrints: settings.includeExtremesInSinglePrints,
    peakValleyRadius: settings.peakValleyRadius,
    peakMinimumProminence: settings.peakMinimumProminence,
    singlePrintMaxTpoCount: settings.singlePrintMaxTpoCount,
    peakValleySensitivity: settings.peakValleySensitivity,
    peakValleyExcludeExtremes: settings.peakValleyExcludeExtremes,
    filterMode: settings.filterMode,
    sessionPreset: settings.sessionPreset,
    customSessionStart: settings.customSessionStart,
    customSessionEnd: settings.customSessionEnd,
    useEndSessionAsStartDay: settings.useEndSessionAsStartDay,
  });
}
