create table if not exists public.waitlist_signups (
  id bigint generated by default as identity primary key,
  email text not null unique,
  source text not null default 'kwantdesk-holding-page',
  created_at timestamptz not null default now(),
  constraint waitlist_signups_email_length check (char_length(email) between 3 and 254),
  constraint waitlist_signups_email_normalized check (email = lower(trim(email))),
  constraint waitlist_signups_email_shape check (email ~* '^[^[:space:]@]+@[^[:space:]@]+\.[^[:space:]@]{2,}$')
);

create index if not exists waitlist_signups_created_at_idx
  on public.waitlist_signups (created_at desc);

alter table public.waitlist_signups enable row level security;

revoke all on table public.waitlist_signups from anon, authenticated;
grant insert on table public.waitlist_signups to anon, authenticated;
grant usage, select on sequence public.waitlist_signups_id_seq to anon, authenticated;

drop policy if exists "Public can join the Kwant Desk waitlist"
  on public.waitlist_signups;
create policy "Public can join the Kwant Desk waitlist"
  on public.waitlist_signups
  for insert
  to anon, authenticated
  with check (
    email = lower(trim(email))
    and char_length(email) between 3 and 254
  );
